#series object in 1 dimensional labelled array

In [9]:
import pandas as pd
s1=pd.Series([1,2,3,4,5])
print(s1)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [4]:
type(s1)

pandas.core.series.Series

In [7]:
s2=pd.Series([1,2,3,4,5],index=['a','b','c','d','e']) #series can be indexed and change to its values
s2

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [11]:
s3=pd.Series({'a':10,'b':10,'c':10})
s3

a    10
b    10
c    10
dtype: int64

In [15]:
#we can change the index position
s4=pd.Series({'a':10,'b':10,'c':10,},index=['b','c','d','a'])
s4

b    10.0
c    10.0
d     NaN
a    10.0
dtype: float64

In [22]:
#extracting the individual values on the series
import pandas as pd
s11=pd.Series([1,2,3,4,5,6,7,8,9])# last element index is -1
s22=pd.Series([10,20,30,40,50,60,70,80,90])

In [23]:
s11[2]

3

In [24]:
s11[2:5]

2    3
3    4
4    5
dtype: int64

In [25]:
s11[-5:]

4    5
5    6
6    7
7    8
8    9
dtype: int64

In [26]:
# basic math operation on series

In [27]:
s11+10

0    11
1    12
2    13
3    14
4    15
5    16
6    17
7    18
8    19
dtype: int64

In [28]:
s11*2

0     2
1     4
2     6
3     8
4    10
5    12
6    14
7    16
8    18
dtype: int64

In [29]:
s11-10

0   -9
1   -8
2   -7
3   -6
4   -5
5   -4
6   -3
7   -2
8   -1
dtype: int64

In [30]:
s11+s22

0    11
1    22
2    33
3    44
4    55
5    66
6    77
7    88
8    99
dtype: int64

In [31]:
#creating a dataframe

In [39]:
import pandas as pd
#dictionary lai list pass garne
df1=pd.DataFrame({"ID":[1,2,3,4,5,6,7,8,9,10],
                 "Name":["Prasanna","Santu","Manjil","Sambad","Prince","Sajal","Riwaz","Sumit","Avisek","Sana"],
                 "Age":[23,24,30,40,25,26,27,28,29,20],
                 "Address":["Patan","Ktm","Bhaktapur","Ktm","Kirtipur","Patan","Godawari","Biratnagar","Nuwakot","Sarlahi"],
                 "Sub":["Dsa","Math","probability","C","JS","Python","C++","NM","CN","DSAP"],
                 "Aim":["Data Engineer","Game Dev","programmer","programmer","programmer","Data Analyst","Frontend Dev","Backend Dev","Politician","hacker"],
                 "Hobby":["Guitar","Football","Football","Cricket","basketball","Sleep","Eat","Travel","Fight","Football"]})

In [45]:
df1

   ID      Name  Age     Address          Sub            Aim       Hobby
0   1  Prasanna   23       Patan          Dsa  Data Engineer      Guitar
1   2     Santu   24         Ktm         Math       Game Dev    Football
2   3    Manjil   30   Bhaktapur  probability     programmer    Football
3   4    Sambad   40         Ktm            C     programmer     Cricket
4   5    Prince   25    Kirtipur           JS     programmer  basketball
5   6     Sajal   26       Patan       Python   Data Analyst       Sleep
6   7     Riwaz   27    Godawari          C++   Frontend Dev         Eat
7   8     Sumit   28  Biratnagar           NM    Backend Dev      Travel
8   9    Avisek   29     Nuwakot           CN     Politician       Fight
9  10      Sana   20     Sarlahi         DSAP         hacker    Football

In [43]:
df1.to_excel('Student1.xlsx',index=False)

In [46]:
df1.head()

   ID      Name  Age    Address          Sub            Aim       Hobby
0   1  Prasanna   23      Patan          Dsa  Data Engineer      Guitar
1   2     Santu   24        Ktm         Math       Game Dev    Football
2   3    Manjil   30  Bhaktapur  probability     programmer    Football
3   4    Sambad   40        Ktm            C     programmer     Cricket
4   5    Prince   25   Kirtipur           JS     programmer  basketball

In [47]:
df1.tail()

   ID    Name  Age     Address     Sub           Aim     Hobby
5   6   Sajal   26       Patan  Python  Data Analyst     Sleep
6   7   Riwaz   27    Godawari     C++  Frontend Dev       Eat
7   8   Sumit   28  Biratnagar      NM   Backend Dev    Travel
8   9  Avisek   29     Nuwakot      CN    Politician     Fight
9  10    Sana   20     Sarlahi    DSAP        hacker  Football

In [48]:
df1.head(10)

   ID      Name  Age     Address          Sub            Aim       Hobby
0   1  Prasanna   23       Patan          Dsa  Data Engineer      Guitar
1   2     Santu   24         Ktm         Math       Game Dev    Football
2   3    Manjil   30   Bhaktapur  probability     programmer    Football
3   4    Sambad   40         Ktm            C     programmer     Cricket
4   5    Prince   25    Kirtipur           JS     programmer  basketball
5   6     Sajal   26       Patan       Python   Data Analyst       Sleep
6   7     Riwaz   27    Godawari          C++   Frontend Dev         Eat
7   8     Sumit   28  Biratnagar           NM    Backend Dev      Travel
8   9    Avisek   29     Nuwakot           CN     Politician       Fight
9  10      Sana   20     Sarlahi         DSAP         hacker    Football

In [73]:
df1.to_csv('Student2.csv', index=False)

In [52]:
df1.describe() #statistical distribution

             ID        Age
count  10.00000  10.000000
mean    5.50000  27.200000
std     3.02765   5.391351
min     1.00000  20.000000
25%     3.25000  24.250000
50%     5.50000  26.500000
75%     7.75000  28.750000
max    10.00000  40.000000

In [58]:
import pandas as pd

df=pd.DataFrame({
    'A':[i for i in range (1,101)],
    'B':[i**2 for i in range (1,101)],
})

In [68]:
pd.set_option('display.max_rows',None)#None garyo bhane sab aauxa , natra 20,20 bahnera dine

In [69]:
pd.set_option('display.max_columns',5)

In [70]:
pd.set_option('display.float_format','{:.2f}'.format)

In [71]:
print(df)

      A      B
0     1      1
1     2      4
2     3      9
3     4     16
4     5     25
5     6     36
6     7     49
7     8     64
8     9     81
9    10    100
10   11    121
11   12    144
12   13    169
13   14    196
14   15    225
15   16    256
16   17    289
17   18    324
18   19    361
19   20    400
20   21    441
21   22    484
22   23    529
23   24    576
24   25    625
25   26    676
26   27    729
27   28    784
28   29    841
29   30    900
30   31    961
31   32   1024
32   33   1089
33   34   1156
34   35   1225
35   36   1296
36   37   1369
37   38   1444
38   39   1521
39   40   1600
40   41   1681
41   42   1764
42   43   1849
43   44   1936
44   45   2025
45   46   2116
46   47   2209
47   48   2304
48   49   2401
49   50   2500
50   51   2601
51   52   2704
52   53   2809
53   54   2916
54   55   3025
55   56   3136
56   57   3249
57   58   3364
58   59   3481
59   60   3600
60   61   3721
61   62   3844
62   63   3969
63   64   4096
64   65   4225
65   66   4356
66   67   4489
67   68   4624
68   69   4761
69   70   4900
70   71   5041
71   72   5184
72   73   5329
73   74   5476
74   75   5625
75   76   5776
76   77   5929
77   78   6084
78   79   6241
79   80   6400
80   81   6561
81   82   6724
82   83   6889
83   84   7056
84   85   7225
85   86   7396
86   87   7569
87   88   7744
88   89   7921
89   90   8100
90   91   8281
91   92   8464
92   93   8649
93   94   8836
94   95   9025
95   96   9216
96   97   9409
97   98   9604
98   99   9801
99  100  10000

In [74]:
#working with datasets

In [98]:
import pandas as pd
df=pd.read_csv('Data_Sets/iris.csv')

In [99]:

df.head(60)

    sepal_length  sepal_width  petal_length  petal_width     species
0           5.10         3.50          1.40         0.20      setosa
1           4.90         3.00          1.40         0.20      setosa
2           4.70         3.20          1.30         0.20      setosa
3           4.60         3.10          1.50         0.20      setosa
4           5.00         3.60          1.40         0.20      setosa
5           5.40         3.90          1.70         0.40      setosa
6           4.60         3.40          1.40         0.30      setosa
7           5.00         3.40          1.50         0.20      setosa
8           4.40         2.90          1.40         0.20      setosa
9           4.90         3.10          1.50         0.10      setosa
10          5.40         3.70          1.50         0.20      setosa
11          4.80         3.40          1.60         0.20      setosa
12          4.80         3.00          1.40         0.10      setosa
13          4.30         3.00          1.10         0.10      setosa
14          5.80         4.00          1.20         0.20      setosa
15          5.70         4.40          1.50         0.40      setosa
16          5.40         3.90          1.30         0.40      setosa
17          5.10         3.50          1.40         0.30      setosa
18          5.70         3.80          1.70         0.30      setosa
19          5.10         3.80          1.50         0.30      setosa
20          5.40         3.40          1.70         0.20      setosa
21          5.10         3.70          1.50         0.40      setosa
22          4.60         3.60          1.00         0.20      setosa
23          5.10         3.30          1.70         0.50      setosa
24          4.80         3.40          1.90         0.20      setosa
25          5.00         3.00          1.60         0.20      setosa
26          5.00         3.40          1.60         0.40      setosa
27          5.20         3.50          1.50         0.20      setosa
28          5.20         3.40          1.40         0.20      setosa
29          4.70         3.20          1.60         0.20      setosa
30          4.80         3.10          1.60         0.20      setosa
31          5.40         3.40          1.50         0.40      setosa
32          5.20         4.10          1.50         0.10      setosa
33          5.50         4.20          1.40         0.20      setosa
34          4.90         3.10          1.50         0.10      setosa
35          5.00         3.20          1.20         0.20      setosa
36          5.50         3.50          1.30         0.20      setosa
37          4.90         3.10          1.50         0.10      setosa
38          4.40         3.00          1.30         0.20      setosa
39          5.10         3.40          1.50         0.20      setosa
40          5.00         3.50          1.30         0.30      setosa
41          4.50         2.30          1.30         0.30      setosa
42          4.40         3.20          1.30         0.20      setosa
43          5.00         3.50          1.60         0.60      setosa
44          5.10         3.80          1.90         0.40      setosa
45          4.80         3.00          1.40         0.30      setosa
46          5.10         3.80          1.60         0.20      setosa
47          4.60         3.20          1.40         0.20      setosa
48          5.30         3.70          1.50         0.20      setosa
49          5.00         3.30          1.40         0.20      setosa
50          7.00         3.20          4.70         1.40  versicolor
51          6.40         3.20          4.50         1.50  versicolor
52          6.90         3.10          4.90         1.50  versicolor
53          5.50         2.30          4.00         1.30  versicolor
54          6.50         2.80          4.60         1.50  versicolor
55          5.70         2.80          4.50         1.30  versicolor
56          6.30         3.30          4.70         1.60  versicolor
57          4.90         2.40          3.30         1.00  versicolor
58          6.60         2.90          4.60         1.30  versicolor
59          5.20         2.70          3.90         1.40  versicolor

In [100]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [101]:
df.tail()

     sepal_length  sepal_width  petal_length  petal_width    species
145          6.70         3.00          5.20         2.30  virginica
146          6.30         2.50          5.00         1.90  virginica
147          6.50         3.00          5.20         2.00  virginica
148          6.20         3.40          5.40         2.30  virginica
149          5.90         3.00          5.10         1.80  virginica

In [102]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count        150.00       150.00        150.00       150.00
mean           5.84         3.05          3.76         1.20
std            0.83         0.43          1.76         0.76
min            4.30         2.00          1.00         0.10
25%            5.10         2.80          1.60         0.30
50%            5.80         3.00          4.35         1.30
75%            6.40         3.30          5.10         1.80
max            7.90         4.40          6.90         2.50

In [103]:
df.iloc[0:3,0:3] #iloc is exclusive (3rd wala row ,column exclusive hunxa) !!!important topic in ML

   sepal_length  sepal_width  petal_length
0          5.10         3.50          1.40
1          4.90         3.00          1.40
2          4.70         3.20          1.30

In [104]:
df.loc[5:10,('petal_length','petal_width')] #loc is inclusive method

    petal_length  petal_width
5           1.70         0.40
6           1.40         0.30
7           1.50         0.20
8           1.40         0.20
9           1.50         0.10
10          1.50         0.20

In [193]:
df.drop(columns=['sepal_length','petal_length'],axis=1)

     sepal_width  petal_width     species  sepal_area sepal_length_category
0           3.50         0.20      setosa       17.85                 short
1           3.00         0.20      setosa       14.70                 short
2           3.20         0.20      setosa       15.04                 short
3           3.10         0.20      setosa       14.26                 short
4           3.60         0.20      setosa       18.00                 short
5           3.90         0.40      setosa       21.06                 short
6           3.40         0.30      setosa       15.64                 short
7           3.40         0.20      setosa       17.00                 short
8           2.90         0.20      setosa       12.76                 short
9           3.10         0.10      setosa       15.19                 short
10          3.70         0.20      setosa       19.98                 short
11          3.40         0.20      setosa       16.32                 short
12          3.00         0.10      setosa       14.40                 short
13          3.00         0.10      setosa       12.90                 short
14          4.00         0.20      setosa       23.20                medium
15          4.40         0.40      setosa       25.08                medium
16          3.90         0.40      setosa       21.06                 short
17          3.50         0.30      setosa       17.85                 short
18          3.80         0.30      setosa       21.66                medium
19          3.80         0.30      setosa       19.38                 short
20          3.40         0.20      setosa       18.36                 short
21          3.70         0.40      setosa       18.87                 short
22          3.60         0.20      setosa       16.56                 short
23          3.30         0.50      setosa       16.83                 short
24          3.40         0.20      setosa       16.32                 short
25          3.00         0.20      setosa       15.00                 short
26          3.40         0.40      setosa       17.00                 short
27          3.50         0.20      setosa       18.20                 short
28          3.40         0.20      setosa       17.68                 short
29          3.20         0.20      setosa       15.04                 short
30          3.10         0.20      setosa       14.88                 short
31          3.40         0.40      setosa       18.36                 short
32          4.10         0.10      setosa       21.32                 short
33          4.20         0.20      setosa       23.10                medium
34          3.10         0.10      setosa       15.19                 short
35          3.20         0.20      setosa       16.00                 short
36          3.50         0.20      setosa       19.25                medium
37          3.10         0.10      setosa       15.19                 short
38          3.00         0.20      setosa       13.20                 short
39          3.40         0.20      setosa       17.34                 short
40          3.50         0.30      setosa       17.50                 short
41          2.30         0.30      setosa       10.35                 short
42          3.20         0.20      setosa       14.08                 short
43          3.50         0.60      setosa       17.50                 short
44          3.80         0.40      setosa       19.38                 short
45          3.00         0.30      setosa       14.40                 short
46          3.80         0.20      setosa       19.38                 short
47          3.20         0.20      setosa       14.72                 short
48          3.70         0.20      setosa       19.61                 short
49          3.30         0.20      setosa       16.50                 short
50          3.20         1.40  versicolor       22.40                  long
51          3.20         1.50  versicolor       20.48                medium
52          3.10         1.50  versicolor       21.39                  long
53          2.30         1.30  versicolor       12.65                medium
54          2.80         1.50  versicolor       18.20                  long
55          2.80         1.30  versicolor       15.96                medium
56          3.30         1.60  versicolor       20.79                medium
57          2.40         1.00  versicolor       11.76                 short
58          2.90         1.30  versicolor       19.14                  long
59          2.70         1.40  versicolor       14.04                 short
60          2.00         1.00  versicolor       10.00                 short
61          3.00         1.50  versicolor       17.70                medium
62          2.20         1.00  versicolor       13.20                medium
63          2.90         1.40  versicolor       17.69                medium
64          2.90         1.30  versicolor       16.24                medium
65          3.10         1.40  versicolor       20.77                  long
66          3.00         1.50  versicolor       16.80                medium
67          2.70         1.00  versicolor       15.66                medium
68          2.20         1.50  versicolor       13.64                medium
69          2.50         1.10  versicolor       14.00                medium
70          3.20         1.80  versicolor       18.88                medium
71          2.80         1.30  versicolor       17.08                medium
72          2.50         1.50  versicolor       15.75                medium
73          2.80         1.20  versicolor       17.08                medium
74          2.90         1.30  versicolor       18.56                medium
75          3.00         1.40  versicolor       19.80                  long
76          2.80         1.40  versicolor       19.04                  long
77          3.00         1.70  versicolor       20.10                  long
78          2.90         1.50  versicolor       17.40                medium
79          2.60         1.00  versicolor       14.82                medium
80          2.40         1.10  versicolor       13.20                medium
81          2.40         1.00  versicolor       13.20                medium
82          2.70         1.20  versicolor       15.66                medium
83          2.70         1.60  versicolor       16.20                medium
84          3.00         1.50  versicolor       16.20                 short
85          3.40         1.60  versicolor       20.40                medium
86          3.10         1.50  versicolor       20.77                  long
87          2.30         1.30  versicolor       14.49                medium
88          3.00         1.30  versicolor       16.80                medium
89          2.50         1.30  versicolor       13.75                medium
90          2.60         1.20  versicolor       14.30                medium
91          3.00         1.40  versicolor       18.30                medium
92          2.60         1.20  versicolor       15.08                medium
93          2.30         1.00  versicolor       11.50                 short
94          2.70         1.30  versicolor       15.12                medium
95          3.00         1.20  versicolor       17.10                medium
96          2.90         1.30  versicolor       16.53                medium
97          2.90         1.30  versicolor       17.98                medium
98          2.50         1.10  versicolor       12.75                 short
99          2.80         1.30  versicolor       15.96                medium
100         3.30         2.50   virginica       20.79                medium
101         2.70         1.90   virginica       15.66                medium
102         3.00         2.10   virginica       21.30                  long
103         2.90         1.80   virginica       18.27                medium
104         3.00         2.20   virginica       19.50                  long
105         3.00         2.10   virginica       22.80                  long
106         2.50         1.70   virginica       12.25                 short
107         2.90         1.80   virginica       21.17                  long
108         2.50         1.80   virginica       16.75                  long
109         3.60         2.50   virginica       25.92                  long
110         3.20         2.00   virginica       20.80                  long
111         2.70         1.90   virginica       17.28                medium
112         3.00         2.10   virginica       20.40                  long
113         2.50         2.00   virginica       14.25                medium
114         2.80         2.40   virginica       16.24                medium
115         3.20         2.30   virginica       20.48                medium
116         3.00         1.80   virginica       19.50                  long
117         3.80         2.20   virginica       29.26                  long
118         2.60         2.30   virginica       20.02                  long
119         2.20         1.50   virginica       13.20                medium
120         3.20         2.30   virginica       22.08                  long
121         2.80         2.00   virginica       15.68                medium
122         2.80         2.00   virginica       21.56                  long
123         2.70         1.80   virginica       17.01                medium
124         3.30         2.10   virginica       22.11                  long
125         3.20         1.80   virginica       23.04                  long
126         2.80         1.80   virginica       17.36                medium
127         3.00         1.80   virginica       18.30                medium
128         2.80         2.10   virginica       17.92                medium
129         3.00         1.60   virginica       21.60                  long
130         2.80         1.90   virginica       20.72                  long
131         3.80         2.00   virginica       30.02                  long
132         2.80         2.20   virginica       17.92                medium
133         2.80         1.50   virginica       17.64                medium
134         2.60         1.40   virginica       15.86                medium
135         3.00         2.30   virginica       23.10                  long
136         3.40         2.40   virginica       21.42                medium
137         3.10         1.80   virginica       19.84                medium
138         3.00         1.80   virginica       18.00                medium
139         3.10         2.10   virginica       21.39                  long
140         3.10         2.40   virginica       20.77                  long
141         3.10         2.30   virginica       21.39                  long
142         2.70         1.90   virginica       15.66                medium
143         3.20         2.30   virginica       21.76                  long
144         3.30         2.50   virginica       22.11                  long
145         3.00         2.30   virginica       20.10                  long
146         2.50         1.90   virginica       15.75                medium
147         3.00         2.00   virginica       19.50                  long
148         3.40         2.30   virginica       21.08                medium
149         3.00         1.80   virginica       17.70                medium

In [194]:
df.head()

   sepal_length  sepal_width  ...  sepal_area  sepal_length_category
0          5.10         3.50  ...       17.85                  short
1          4.90         3.00  ...       14.70                  short
2          4.70         3.20  ...       15.04                  short
3          4.60         3.10  ...       14.26                  short
4          5.00         3.60  ...       18.00                  short

[5 rows x 7 columns]

In [195]:
#df.drop(columns=['sepal_length','petal_length'],axis=1,inplace=True) 
# df =df.drop(..._ bhanera dinu pardaina if we use inplace

In [196]:
df.head()

   sepal_length  sepal_width  ...  sepal_area  sepal_length_category
0          5.10         3.50  ...       17.85                  short
1          4.90         3.00  ...       14.70                  short
2          4.70         3.20  ...       15.04                  short
3          4.60         3.10  ...       14.26                  short
4          5.00         3.60  ...       18.00                  short

[5 rows x 7 columns]

In [197]:
df.head()

   sepal_length  sepal_width  ...  sepal_area  sepal_length_category
0          5.10         3.50  ...       17.85                  short
1          4.90         3.00  ...       14.70                  short
2          4.70         3.20  ...       15.04                  short
3          4.60         3.10  ...       14.26                  short
4          5.00         3.60  ...       18.00                  short

[5 rows x 7 columns]

In [198]:
def double_make(s):
    return s*2

In [199]:
df[['sepal_length','petal_width']].apply(double_make)

     sepal_length  petal_width
0           10.20         0.40
1            9.80         0.40
2            9.40         0.40
3            9.20         0.40
4           10.00         0.40
5           10.80         0.80
6            9.20         0.60
7           10.00         0.40
8            8.80         0.40
9            9.80         0.20
10          10.80         0.40
11           9.60         0.40
12           9.60         0.20
13           8.60         0.20
14          11.60         0.40
15          11.40         0.80
16          10.80         0.80
17          10.20         0.60
18          11.40         0.60
19          10.20         0.60
20          10.80         0.40
21          10.20         0.80
22           9.20         0.40
23          10.20         1.00
24           9.60         0.40
25          10.00         0.40
26          10.00         0.80
27          10.40         0.40
28          10.40         0.40
29           9.40         0.40
30           9.60         0.40
31          10.80         0.80
32          10.40         0.20
33          11.00         0.40
34           9.80         0.20
35          10.00         0.40
36          11.00         0.40
37           9.80         0.20
38           8.80         0.40
39          10.20         0.40
40          10.00         0.60
41           9.00         0.60
42           8.80         0.40
43          10.00         1.20
44          10.20         0.80
45           9.60         0.60
46          10.20         0.40
47           9.20         0.40
48          10.60         0.40
49          10.00         0.40
50          14.00         2.80
51          12.80         3.00
52          13.80         3.00
53          11.00         2.60
54          13.00         3.00
55          11.40         2.60
56          12.60         3.20
57           9.80         2.00
58          13.20         2.60
59          10.40         2.80
60          10.00         2.00
61          11.80         3.00
62          12.00         2.00
63          12.20         2.80
64          11.20         2.60
65          13.40         2.80
66          11.20         3.00
67          11.60         2.00
68          12.40         3.00
69          11.20         2.20
70          11.80         3.60
71          12.20         2.60
72          12.60         3.00
73          12.20         2.40
74          12.80         2.60
75          13.20         2.80
76          13.60         2.80
77          13.40         3.40
78          12.00         3.00
79          11.40         2.00
80          11.00         2.20
81          11.00         2.00
82          11.60         2.40
83          12.00         3.20
84          10.80         3.00
85          12.00         3.20
86          13.40         3.00
87          12.60         2.60
88          11.20         2.60
89          11.00         2.60
90          11.00         2.40
91          12.20         2.80
92          11.60         2.40
93          10.00         2.00
94          11.20         2.60
95          11.40         2.40
96          11.40         2.60
97          12.40         2.60
98          10.20         2.20
99          11.40         2.60
100         12.60         5.00
101         11.60         3.80
102         14.20         4.20
103         12.60         3.60
104         13.00         4.40
105         15.20         4.20
106          9.80         3.40
107         14.60         3.60
108         13.40         3.60
109         14.40         5.00
110         13.00         4.00
111         12.80         3.80
112         13.60         4.20
113         11.40         4.00
114         11.60         4.80
115         12.80         4.60
116         13.00         3.60
117         15.40         4.40
118         15.40         4.60
119         12.00         3.00
120         13.80         4.60
121         11.20         4.00
122         15.40         4.00
123         12.60         3.60
124         13.40         4.20
125         14.40         3.60
126         12.40         3.60
127         12.20         3.60
128         12.80         4.20
129         14.40         3.20
130         14.80         3.80
131         15.80         4.00
132         12.80         4.40
133         12.60         3.00
134         12.20         2.80
135         15.40         4.60
136         12.60         4.80
137         12.80         3.60
138         12.00         3.60
139         13.80         4.20
140         13.40         4.80
141         13.80         4.60
142         11.60         3.80
143         13.60         4.60
144         13.40         5.00
145         13.40         4.60
146         12.60         3.80
147         13.00         4.00
148         12.40         4.60
149         11.80         3.60

In [200]:
df['species'].value_counts()# to count frequency

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [201]:
df.sort_values(by='petal_length') #sorting in ascending order

     sepal_length  sepal_width  ...  sepal_area  sepal_length_category
22           4.60         3.60  ...       16.56                  short
13           4.30         3.00  ...       12.90                  short
14           5.80         4.00  ...       23.20                 medium
35           5.00         3.20  ...       16.00                  short
36           5.50         3.50  ...       19.25                 medium
40           5.00         3.50  ...       17.50                  short
38           4.40         3.00  ...       13.20                  short
42           4.40         3.20  ...       14.08                  short
2            4.70         3.20  ...       15.04                  short
41           4.50         2.30  ...       10.35                  short
16           5.40         3.90  ...       21.06                  short
17           5.10         3.50  ...       17.85                  short
45           4.80         3.00  ...       14.40                  short
33           5.50         4.20  ...       23.10                 medium
28           5.20         3.40  ...       17.68                  short
47           4.60         3.20  ...       14.72                  short
49           5.00         3.30  ...       16.50                  short
0            5.10         3.50  ...       17.85                  short
4            5.00         3.60  ...       18.00                  short
1            4.90         3.00  ...       14.70                  short
12           4.80         3.00  ...       14.40                  short
6            4.60         3.40  ...       15.64                  short
8            4.40         2.90  ...       12.76                  short
34           4.90         3.10  ...       15.19                  short
10           5.40         3.70  ...       19.98                  short
32           5.20         4.10  ...       21.32                  short
31           5.40         3.40  ...       18.36                  short
15           5.70         4.40  ...       25.08                 medium
27           5.20         3.50  ...       18.20                  short
9            4.90         3.10  ...       15.19                  short
7            5.00         3.40  ...       17.00                  short
3            4.60         3.10  ...       14.26                  short
48           5.30         3.70  ...       19.61                  short
21           5.10         3.70  ...       18.87                  short
19           5.10         3.80  ...       19.38                  short
39           5.10         3.40  ...       17.34                  short
37           4.90         3.10  ...       15.19                  short
30           4.80         3.10  ...       14.88                  short
29           4.70         3.20  ...       15.04                  short
11           4.80         3.40  ...       16.32                  short
26           5.00         3.40  ...       17.00                  short
25           5.00         3.00  ...       15.00                  short
46           5.10         3.80  ...       19.38                  short
43           5.00         3.50  ...       17.50                  short
18           5.70         3.80  ...       21.66                 medium
5            5.40         3.90  ...       21.06                  short
23           5.10         3.30  ...       16.83                  short
20           5.40         3.40  ...       18.36                  short
24           4.80         3.40  ...       16.32                  short
44           5.10         3.80  ...       19.38                  short
98           5.10         2.50  ...       12.75                  short
93           5.00         2.30  ...       11.50                  short
57           4.90         2.40  ...       11.76                  short
60           5.00         2.00  ...       10.00                  short
79           5.70         2.60  ...       14.82                 medium
64           5.60         2.90  ...       16.24                 medium
81           5.50         2.40  ...       13.20                 medium
80           5.50         2.40  ...       13.20                 medium
69           5.60         2.50  ...       14.00                 medium
82           5.80         2.70  ...       15.66                 medium
59           5.20         2.70  ...       14.04                  short
62           6.00         2.20  ...       13.20                 medium
92           5.80         2.60  ...       15.08                 medium
89           5.50         2.50  ...       13.75                 medium
53           5.50         2.30  ...       12.65                 medium
71           6.10         2.80  ...       17.08                 medium
88           5.60         3.00  ...       16.80                 medium
67           5.80         2.70  ...       15.66                 medium
99           5.70         2.80  ...       15.96                 medium
61           5.90         3.00  ...       17.70                 medium
96           5.70         2.90  ...       16.53                 medium
94           5.60         2.70  ...       15.12                 medium
95           5.70         3.00  ...       17.10                 medium
97           6.20         2.90  ...       17.98                 medium
74           6.40         2.90  ...       18.56                 medium
75           6.60         3.00  ...       19.80                   long
90           5.50         2.60  ...       14.30                 medium
65           6.70         3.10  ...       20.77                   long
87           6.30         2.30  ...       14.49                 medium
106          4.90         2.50  ...       12.25                  short
51           6.40         3.20  ...       20.48                 medium
78           6.00         2.90  ...       17.40                 medium
55           5.70         2.80  ...       15.96                 medium
68           6.20         2.20  ...       13.64                 medium
84           5.40         3.00  ...       16.20                  short
85           6.00         3.40  ...       20.40                 medium
66           5.60         3.00  ...       16.80                 medium
54           6.50         2.80  ...       18.20                   long
91           6.10         3.00  ...       18.30                 medium
58           6.60         2.90  ...       19.14                   long
63           6.10         2.90  ...       17.69                 medium
56           6.30         3.30  ...       20.79                 medium
73           6.10         2.80  ...       17.08                 medium
50           7.00         3.20  ...       22.40                   long
86           6.70         3.10  ...       20.77                   long
70           5.90         3.20  ...       18.88                 medium
138          6.00         3.00  ...       18.00                 medium
76           6.80         2.80  ...       19.04                   long
126          6.20         2.80  ...       17.36                 medium
72           6.30         2.50  ...       15.75                 medium
52           6.90         3.10  ...       21.39                   long
121          5.60         2.80  ...       15.68                 medium
123          6.30         2.70  ...       17.01                 medium
127          6.10         3.00  ...       18.30                 medium
146          6.30         2.50  ...       15.75                 medium
119          6.00         2.20  ...       13.20                 medium
113          5.70         2.50  ...       14.25                 medium
77           6.70         3.00  ...       20.10                   long
141          6.90         3.10  ...       21.39                   long
114          5.80         2.80  ...       16.24                 medium
133          6.30         2.80  ...       17.64                 medium
142          5.80         2.70  ...       15.66                 medium
149          5.90         3.00  ...       17.70                 medium
110          6.50         3.20  ...       20.80                   long
83           6.00         2.70  ...       16.20                 medium
101          5.80         2.70  ...       15.66                 medium
147          6.50         3.00  ...       19.50                   long
145          6.70         3.00  ...       20.10                   long
111          6.40         2.70  ...       17.28                 medium
115          6.40         3.20  ...       20.48                 medium
139          6.90         3.10  ...       21.39                   long
148          6.20         3.40  ...       21.08                 medium
137          6.40         3.10  ...       19.84                 medium
112          6.80         3.00  ...       20.40                   long
116          6.50         3.00  ...       19.50                   long
136          6.30         3.40  ...       21.42                 medium
140          6.70         3.10  ...       20.77                   long
128          6.40         2.80  ...       17.92                 medium
134          6.10         2.60  ...       15.86                 medium
103          6.30         2.90  ...       18.27                 medium
132          6.40         2.80  ...       17.92                 medium
144          6.70         3.30  ...       22.11                   long
120          6.90         3.20  ...       22.08                   long
124          6.70         3.30  ...       22.11                   long
108          6.70         2.50  ...       16.75                   long
129          7.20         3.00  ...       21.60                   long
104          6.50         3.00  ...       19.50                   long
102          7.10         3.00  ...       21.30                   long
143          6.80         3.20  ...       21.76                   long
100          6.30         3.30  ...       20.79                 medium
125          7.20         3.20  ...       23.04                   long
130          7.40         2.80  ...       20.72                   long
135          7.70         3.00  ...       23.10                   long
109          7.20         3.60  ...       25.92                   long
107          7.30         2.90  ...       21.17                   long
131          7.90         3.80  ...       30.02                   long
105          7.60         3.00  ...       22.80                   long
117          7.70         3.80  ...       29.26                   long
122          7.70         2.80  ...       21.56                   long
118          7.70         2.60  ...       20.02                   long

[150 rows x 7 columns]

In [202]:
df.sort_values(by='petal_length',ascending=False) #sorting in descending order

     sepal_length  sepal_width  ...  sepal_area  sepal_length_category
118          7.70         2.60  ...       20.02                   long
122          7.70         2.80  ...       21.56                   long
117          7.70         3.80  ...       29.26                   long
105          7.60         3.00  ...       22.80                   long
131          7.90         3.80  ...       30.02                   long
107          7.30         2.90  ...       21.17                   long
130          7.40         2.80  ...       20.72                   long
109          7.20         3.60  ...       25.92                   long
135          7.70         3.00  ...       23.10                   long
100          6.30         3.30  ...       20.79                 medium
125          7.20         3.20  ...       23.04                   long
102          7.10         3.00  ...       21.30                   long
143          6.80         3.20  ...       21.76                   long
129          7.20         3.00  ...       21.60                   long
108          6.70         2.50  ...       16.75                   long
104          6.50         3.00  ...       19.50                   long
124          6.70         3.30  ...       22.11                   long
144          6.70         3.30  ...       22.11                   long
120          6.90         3.20  ...       22.08                   long
132          6.40         2.80  ...       17.92                 medium
140          6.70         3.10  ...       20.77                   long
103          6.30         2.90  ...       18.27                 medium
128          6.40         2.80  ...       17.92                 medium
134          6.10         2.60  ...       15.86                 medium
136          6.30         3.40  ...       21.42                 medium
112          6.80         3.00  ...       20.40                   long
116          6.50         3.00  ...       19.50                   long
137          6.40         3.10  ...       19.84                 medium
148          6.20         3.40  ...       21.08                 medium
139          6.90         3.10  ...       21.39                   long
115          6.40         3.20  ...       20.48                 medium
111          6.40         2.70  ...       17.28                 medium
145          6.70         3.00  ...       20.10                   long
147          6.50         3.00  ...       19.50                   long
101          5.80         2.70  ...       15.66                 medium
83           6.00         2.70  ...       16.20                 medium
110          6.50         3.20  ...       20.80                   long
149          5.90         3.00  ...       17.70                 medium
114          5.80         2.80  ...       16.24                 medium
133          6.30         2.80  ...       17.64                 medium
142          5.80         2.70  ...       15.66                 medium
141          6.90         3.10  ...       21.39                   long
113          5.70         2.50  ...       14.25                 medium
119          6.00         2.20  ...       13.20                 medium
77           6.70         3.00  ...       20.10                   long
146          6.30         2.50  ...       15.75                 medium
52           6.90         3.10  ...       21.39                   long
72           6.30         2.50  ...       15.75                 medium
127          6.10         3.00  ...       18.30                 medium
121          5.60         2.80  ...       15.68                 medium
123          6.30         2.70  ...       17.01                 medium
138          6.00         3.00  ...       18.00                 medium
76           6.80         2.80  ...       19.04                   long
70           5.90         3.20  ...       18.88                 medium
126          6.20         2.80  ...       17.36                 medium
63           6.10         2.90  ...       17.69                 medium
86           6.70         3.10  ...       20.77                   long
56           6.30         3.30  ...       20.79                 medium
73           6.10         2.80  ...       17.08                 medium
50           7.00         3.20  ...       22.40                   long
58           6.60         2.90  ...       19.14                   long
91           6.10         3.00  ...       18.30                 medium
54           6.50         2.80  ...       18.20                   long
85           6.00         3.40  ...       20.40                 medium
55           5.70         2.80  ...       15.96                 medium
84           5.40         3.00  ...       16.20                  short
66           5.60         3.00  ...       16.80                 medium
78           6.00         2.90  ...       17.40                 medium
68           6.20         2.20  ...       13.64                 medium
106          4.90         2.50  ...       12.25                  short
51           6.40         3.20  ...       20.48                 medium
90           5.50         2.60  ...       14.30                 medium
87           6.30         2.30  ...       14.49                 medium
75           6.60         3.00  ...       19.80                   long
65           6.70         3.10  ...       20.77                   long
74           6.40         2.90  ...       18.56                 medium
97           6.20         2.90  ...       17.98                 medium
95           5.70         3.00  ...       17.10                 medium
94           5.60         2.70  ...       15.12                 medium
61           5.90         3.00  ...       17.70                 medium
96           5.70         2.90  ...       16.53                 medium
99           5.70         2.80  ...       15.96                 medium
67           5.80         2.70  ...       15.66                 medium
88           5.60         3.00  ...       16.80                 medium
53           5.50         2.30  ...       12.65                 medium
62           6.00         2.20  ...       13.20                 medium
71           6.10         2.80  ...       17.08                 medium
89           5.50         2.50  ...       13.75                 medium
92           5.80         2.60  ...       15.08                 medium
82           5.80         2.70  ...       15.66                 medium
59           5.20         2.70  ...       14.04                  short
69           5.60         2.50  ...       14.00                 medium
80           5.50         2.40  ...       13.20                 medium
81           5.50         2.40  ...       13.20                 medium
64           5.60         2.90  ...       16.24                 medium
60           5.00         2.00  ...       10.00                  short
79           5.70         2.60  ...       14.82                 medium
93           5.00         2.30  ...       11.50                  short
57           4.90         2.40  ...       11.76                  short
98           5.10         2.50  ...       12.75                  short
24           4.80         3.40  ...       16.32                  short
44           5.10         3.80  ...       19.38                  short
18           5.70         3.80  ...       21.66                 medium
5            5.40         3.90  ...       21.06                  short
20           5.40         3.40  ...       18.36                  short
23           5.10         3.30  ...       16.83                  short
46           5.10         3.80  ...       19.38                  short
43           5.00         3.50  ...       17.50                  short
25           5.00         3.00  ...       15.00                  short
26           5.00         3.40  ...       17.00                  short
29           4.70         3.20  ...       15.04                  short
11           4.80         3.40  ...       16.32                  short
30           4.80         3.10  ...       14.88                  short
21           5.10         3.70  ...       18.87                  short
32           5.20         4.10  ...       21.32                  short
27           5.20         3.50  ...       18.20                  short
15           5.70         4.40  ...       25.08                 medium
31           5.40         3.40  ...       18.36                  short
19           5.10         3.80  ...       19.38                  short
34           4.90         3.10  ...       15.19                  short
10           5.40         3.70  ...       19.98                  short
37           4.90         3.10  ...       15.19                  short
9            4.90         3.10  ...       15.19                  short
39           5.10         3.40  ...       17.34                  short
7            5.00         3.40  ...       17.00                  short
48           5.30         3.70  ...       19.61                  short
3            4.60         3.10  ...       14.26                  short
12           4.80         3.00  ...       14.40                  short
8            4.40         2.90  ...       12.76                  short
6            4.60         3.40  ...       15.64                  short
17           5.10         3.50  ...       17.85                  short
4            5.00         3.60  ...       18.00                  short
0            5.10         3.50  ...       17.85                  short
1            4.90         3.00  ...       14.70                  short
28           5.20         3.40  ...       17.68                  short
49           5.00         3.30  ...       16.50                  short
33           5.50         4.20  ...       23.10                 medium
47           4.60         3.20  ...       14.72                  short
45           4.80         3.00  ...       14.40                  short
41           4.50         2.30  ...       10.35                  short
2            4.70         3.20  ...       15.04                  short
42           4.40         3.20  ...       14.08                  short
38           4.40         3.00  ...       13.20                  short
40           5.00         3.50  ...       17.50                  short
16           5.40         3.90  ...       21.06                  short
36           5.50         3.50  ...       19.25                 medium
35           5.00         3.20  ...       16.00                  short
14           5.80         4.00  ...       23.20                 medium
13           4.30         3.00  ...       12.90                  short
22           4.60         3.60  ...       16.56                  short

[150 rows x 7 columns]

In [203]:
#sort multiple columns

sorted_data_multiple=df.sort_values(by=['sepal_length','sepal_width'],ascending=[False,True])
print("\n Sorted data by sepal length (descending) Sorted data by sepal length (ascending)")
print(sorted_data_multiple.head())

 Sorted data by sepal length (descending) Sorted data by sepal length (ascending)
     sepal_length  sepal_width  ...  sepal_area  sepal_length_category
131          7.90         3.80  ...       30.02                   long
118          7.70         2.60  ...       20.02                   long
122          7.70         2.80  ...       21.56                   long
135          7.70         3.00  ...       23.10                   long
117          7.70         3.80  ...       29.26                   long

[5 rows x 7 columns]

In [204]:
#filtering the dataset
#sekect rows where petal length > 1.5
filtered_data=df[df['petal_length']>1.5]
print('\n Filtered data (petal_length > 1.5):')
filtered_data.head()

 Filtered data (petal_length > 1.5):

    sepal_length  sepal_width  ...  sepal_area  sepal_length_category
5           5.40         3.90  ...       21.06                  short
11          4.80         3.40  ...       16.32                  short
18          5.70         3.80  ...       21.66                 medium
20          5.40         3.40  ...       18.36                  short
23          5.10         3.30  ...       16.83                  short

[5 rows x 7 columns]

In [205]:
#Grouping by species and calculating means 
grouped_data=df.groupby('species').mean()
print("\n Mean values grouped by species:")
print(grouped_data)

TypeError: agg function failed [how->mean,dtype->object]

In [ ]:
df["sepal_area"]=df["sepal_length"]*df["sepal_width"]
print("\n Dataset with sepal_area column added:")
df.head()

In [ ]:
# example: function to classify sepal length into categories
def classify_sepal_length(length):
    if length < 5.5:
        return 'short'
    elif length <6.5:
        return 'medium'
    else:
        return 'long'
        
#apply function to create a new column 'sepal_length_category'
df['sepal_length_category']=df['sepal_length'].apply(classify_sepal_length)
print("\n Dataset with sepal_length_category column added:")
print(df.head())

In [ ]:
pivot_table=pd.pivot_table(df,values = 'petal_width' ,index='species',columns='sepal_length_category',aggfunc='mean')
print("\n Pivot table of mean petal_width and sepal_length_category")
pivot_table

In [ ]:
# encode species column with one hot encoding: One hot encoding is not necessary for tree based models

encoded_data=pd.get_dummies(df,columns=['species'])
print("\n Datasets with species column encoded:")
print(encoded_data.head())

In [ ]:
concat_data=pd.concat([df,df.copy()],ignore_index=True)
print("Concatenated Data:")
concat_data.head()

In [ ]:
#reshape data using melt
melted_data=pd.melt(df,id_vars=['species'],
                    value_vars=['sepal_length','sepal_width','petal_length','petal_width'])
print("\nMelted Dataset:")
print(melted_data.head(80))

# working with user car datasets

In [ ]:
import pandas as pd

In [ ]:
data=pd.read_csv('Data_Sets/used_cars.csv')

In [ ]:
data

In [ ]:
data.info()

In [ ]:
data.shape

In [ ]:
data.columns

In [ ]:
print(list(data.columns))

In [ ]:
data.describe()

In [ ]:
columns_to_check=data.columns

In [ ]:
for col in data.columns:
    print(f"\n Value Counts for '{col}'")

In [ ]:
#check the numnber of duplicates
duplicates=data.duplicated().sum()
print(f"Number of duplicate rows :{duplicates}")

In [207]:
data.isnull().sum()

brand             0
model             0
model_year        0
milage            0
fuel_type       170
engine            0
transmission      0
ext_col           0
int_col           0
accident        113
clean_title     596
price             0
dtype: int64

In [206]:

missing_columns={}
for col in data.columns:
    missing_count=data[col].isnull().sum()
    if missing_count > 0:
        missing_percentage=(missing_count/len(data))*100
        missing_columns[col]=round(missing_percentage, 2)

print("\nMissing coulumns with percentage is ")

for col,percentage in missing_columns.items():
    print(f'{col}: {percentage}%')

Missing coulumns with percentage is
fuel_type: 4.24%
accident: 2.82%
clean_title: 14.87%